version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/172.17.0.1:40001,172.17.0.1:40002,172.17.0.1:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017
